### ISSUE TITLE
Add to DMS Demo site: Cookie consent, Question slider and Privacy policy 

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-demo#14]

**Comment by herflis** [comment]
[preview](https://deploy-preview-398--sn-dms-demo-dev.netlify.com/#/login)

@kultsar I have some questions:
- Where should I place the link to the privacy policy (the page is ready [here](https://deploy-preview-398--sn-dms-demo-dev.netlify.com/#/privacypolicy))?
- How should the privacy policy page look like?
- How will the user navigate back from the privacy policy page to the dms?

**Comment by kultsar** [comment]
**Where to place the link to the privacy policy**
PP should be easily visible and accessible. At a minimum I think we would satisfy this requirement by adding the link only to the login page: "Please log in, or register!" --> "Please check out our privacy policy, then log in, or register!". (For me this would be ok, but let's discuss if this feels too minimal. At the moment I can only imagine a footer as a better solution on both login and internal pages, with the same content as the one on sensenet.com ("© Copyright Sense/Net Inc · Powered by sensenet · Privacy Policy"). 

**How should the privacy policy page look like**
It is perfect for me for our purposes as it looks now.

**How will the user navigate back from the privacy policy page to the dms**
Just close the window, I would add no other navigation now.

**Other notes**

pp text
- "www.community.sensenet.com" --> "dms.demo.sensenet.com"
- Data processors table: remove Linkedin and Youtube. Keep Analytics, Hotjar and an eucookie. Even if we do not use them now, we may, and the sentence above the table also says we "may use" these.

Cookie popup
- Should add "This website uses cookies" title.
- "More information" link should point at https://www.eucookie.eu/en/cookieinfo/?url=dms.demo.sensenet.com.
- Should add "Change settings" link that unhides "I allow this website to use the following cookies" and Required, Analytical, Marketing and Preferences checkboxes.

**Comment by kultsar** [comment]
We can remove the surveymonkey popup, sorry, I forgot to add this to the above list.
