### ISSUE TITLE
Share Sample document.docx contents mutually between alba and businesscat users

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-demo#25]
Should configure sharing these documents between alba and businesscat so that automated tests can use them. Also useful for demonstrations.

**Comment by kultsar** [comment]
I think it is not a problem, but Alba's doc is shared with herself as well. Otherwise, the two shares are ok.

**Comment by herflis** [comment]
The GetSharing action returns only businesscat

```
{
  "d": {
    "__count": 1,
    "results": [
      {
        "Id": "f75b487f-fdb4-4cd0-9d20-82b0f42a9486",
        "Token": "businesscat@sensenet.com",
        "Identity": 4811,
        "Mode": "Private",
        "Level": "Open",
        "CreatorId": 1,
        "ShareDate": "2018-10-16T00:40:15Z"
      }
    ]
  }
}
```

so I think this is not related to this issue
