### ISSUE TITLE
[demo] Demo site for testing the medium plan

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-demo#38]
Medium/business plan will be a package with 25 users, 25000 content, 5 groups

url: https://dev10.demo.sensenet.com

**import**: https://github.com/SenseNet/sn-demo/tree/master/src/snadmin/install-demo-business
**doksik**: \Products\SNaaS\import-docs-business
**demo workspace names:**  \Products\SNaaS\business-demo-wsnames.json 

The repo will contain 320 workspaces with the following libraries and folders:
- a doclib with 18 various type of files
- a tasklist with 10 tasks
- a memolist with 10 memos
- a group folder with the 3 built-in local groups
- a blog folder with 10 blog posts
- a news folder with 10 articles
- an eventcalendar with 10 events

**Comment by Ishaan28malik** [comment]
Hey is it still open , please assign this to me .
@herflis 
Also please explain if I am supposed to add all these libraries and folders?

**Comment by herflis** [comment]
Hy @Ishaan28malik, sorry but this issue is already taken by one of our team members :)

**Comment by Ishaan28malik** [comment]
Ok thanks for the update @herflis 
Good to see it closed.
